# Generated by Django 5.1.5 on 2025-02-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='children_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество детей'),
        ),
        migrations.AddField(
            model_name='booking',
            name='comment',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Комментарий'),
        ),
    ]
