# Generated by Django 5.1.5 on 2025-02-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_children_count_booking_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='edited_by_admin',
            field=models.BooleanField(default=False, verbose_name='Отредактировано администратором'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='children_count',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Количество детей'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(blank=True, default='Активно', max_length=50, null=True, verbose_name='Статус'),
        ),
    ]
