# Generated by Django 5.1.5 on 2025-02-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_edited_by_admin_alter_booking_children_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='edited_by_admin',
        ),
        migrations.AddField(
            model_name='booking',
            name='edited_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отредактировано'),
        ),
    ]
