# Generated by Django 5.1.5 on 2025-02-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_booking_edited_by_admin_booking_edited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', 'На модерации'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено')], default='active', max_length=50, verbose_name='Статус'),
        ),
    ]
