# Generated by Django 5.1.5 on 2025-03-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_amount_booking_booking_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='prepayment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Предоплата'),
        ),
    ]
