# Generated by Django 5.1.5 on 2025-03-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_prepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cashier_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Оплата на кассе'),
        ),
    ]
