# Generated by Django 5.1.5 on 2025-03-21 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_booking_cashier_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='prepayment',
            field=models.BooleanField(default=False, verbose_name='Предоплата'),
        ),
    ]
