# Generated by Django 5.1.5 on 2025-03-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_booking_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('online', 'Онлайн'), ('offline', 'На месте')], default='online', max_length=10, verbose_name='Тип бронирования'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено'), ('completed', 'Завершено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
