# Generated by Django 5.1.5 on 2025-03-23 23:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_alter_booking_booking_type_alter_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_type',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cashier_payment',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='children_count',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='edited_by',
        ),
        migrations.AlterField(
            model_name='booking',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Общая сумма'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='prepayment',
            field=models.BooleanField(default=False, help_text='При активации минимальная сумма 1000 руб', verbose_name='Предоплата'),
        ),
    ]
