# Generated by Django 5.1.5 on 2025-04-03 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_remove_booking_amount_booking_prepayment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='children_count',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество детей'),
        ),
        migrations.AddField(
            model_name='booking',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
