# Generated by Django 5.1.5 on 2025-05-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_booking_children_count_booking_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='event_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('birthday', 'День рождения'), ('vr', 'VR-арена'), ('animation', 'Выездная анимация'), ('other', 'Другое')], default='birthday', max_length=20, verbose_name='Тип бронирования'),
        ),
        migrations.AddField(
            model_name='booking',
            name='custom_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Свой вариант'),
        ),
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Местоположение'),
        ),
    ]
