# Generated by Django 5.1.5 on 2025-05-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_remove_booking_event_name_booking_booking_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_source',
            field=models.CharField(choices=[('website', 'Сайт'), ('telegram', 'Телеграм')], default='website', max_length=20, verbose_name='Источник бронирования'),
        ),
    ]
