# Generated by Django 5.1.5 on 2025-05-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_booking_booking_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='event_name',
            field=models.CharField(default='Новое бронирование', max_length=255, verbose_name='Название мероприятия'),
        ),
    ]
