# Generated by Django 5.1.5 on 2025-05-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_booking_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event_name',
            field=models.CharField(max_length=255, verbose_name='Название мероприятия'),
        ),
    ]
