# Generated by Django 5.1.5 on 2025-05-23 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_alter_booking_event_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-event_date'], 'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booking_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_source',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='prepayment_amount',
        ),
        migrations.AddField(
            model_name='booking',
            name='cashier_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оплата кассиром'),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='children_count',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество детей'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='event_date',
            field=models.DateTimeField(verbose_name='Дата мероприятия'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оплаченная сумма'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='prepayment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Предоплата'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено'), ('completed', 'Завершено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
