# Generated by Django 5.1.5 on 2025-05-23 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
    ]
