# Generated by Django 5.1.5 on 2025-02-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=255, verbose_name='Заголовок сайта')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Мета описание')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключевые слова')),
                ('google_analytics', models.TextField(blank=True, null=True, verbose_name='Код Google Analytics')),
            ],
            options={
                'verbose_name': 'Настройка сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
