# Generated by Django 5.1.5 on 2025-02-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('holiday', 'Праздник'), ('concert', 'Концерт'), ('seminar', 'Семинар'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Тип мероприятия'),
        ),
        migrations.AddField(
            model_name='event',
            name='moderation_status',
            field=models.CharField(choices=[('approved', 'Принято'), ('rejected', 'Отказано'), ('unavailable', 'Недоступно'), ('pending', 'На модерации')], default='pending', max_length=50, verbose_name='Статус модерации'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
