# Generated by Django 5.1.5 on 2025-02-13 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_booking_edited_by_admin_booking_edited_by'),
        ('staff', '0005_event_event_type_event_moderation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.booking', verbose_name='Бронирование'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('holiday', 'Праздник'), ('birthday', 'День рождения'), ('animators', 'Открытые анимации'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Тип мероприятия'),
        ),
    ]
