# Generated by Django 5.1.5 on 2025-02-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_event_booking_alter_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='client_login',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Логин клиента'),
        ),
        migrations.AddField(
            model_name='event',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя клиента'),
        ),
    ]
