# Generated by Django 5.1.5 on 2025-02-17 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_event_client_login_event_client_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='client_login',
        ),
        migrations.RemoveField(
            model_name='event',
            name='client_name',
        ),
    ]
