# Generated by Django 5.1.5 on 2025-03-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_remove_event_client_login_remove_event_client_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(default=0, verbose_name='Максимальное количество участников'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(verbose_name='Дата и время мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='Описание мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('выездные анимации', 'Выездные анимации'), ('открытые анимации', 'Открытые анимации'), ('панорамик', 'Панорамик'), ('другое', 'Другое')], default='другое', max_length=50, verbose_name='Тип мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Изображение мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название мероприятия'),
        ),
    ]
