# Generated by Django 5.1.5 on 2025-05-08 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_booking_children_count_booking_comment'),
        ('staff', '0012_shift_shiftrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date'], 'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterField(
            model_name='event',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.booking', verbose_name='Бронирование'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('выездные анимации', 'Выездные анимации'), ('открытые анимации', 'Открытые анимации'), ('панорамик', 'Панорамик'), ('другое', 'Другое')], max_length=50, verbose_name='Тип мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('main', 'Основная площадка'), ('secondary', 'Дополнительная площадка')], default='main', max_length=100, verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='moderation_status',
            field=models.CharField(choices=[('approved', 'Принято'), ('rejected', 'Отказано'), ('unavailable', 'Недоступно'), ('pending', 'На модерации')], default='pending', max_length=20, verbose_name='Статус модерации'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
