# Generated by Django 5.1.5 on 2025-05-31 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_alter_event_options_alter_event_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftrequest',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий сотрудника'),
        ),
    ]
