# Generated by Django 5.1.5 on 2025-05-31 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_shift_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='date',
            field=models.DateField(verbose_name='Дата смены'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='max_staff',
            field=models.PositiveIntegerField(default=1, verbose_name='Макс. сотрудников'),
        ),
    ]
