# Generated by Django 5.1.5 on 2025-05-31 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0016_alter_shift_date_alter_shift_max_staff'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shiftrequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='shiftrequest',
            name='date',
            field=models.DateField(default='2024-01-01', verbose_name='Дата смены'),
        ),
        migrations.AddField(
            model_name='shiftrequest',
            name='end_time',
            field=models.TimeField(default='18:00', verbose_name='Конец смены'),
        ),
        migrations.AddField(
            model_name='shiftrequest',
            name='role',
            field=models.CharField(choices=[('animator', 'Детский городок'), ('additional', 'Доп. сотрудник'), ('vr_operator', 'VR сотрудник'), ('cashier', 'Кассир (Администратор)')], default='animator', max_length=20, verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='shiftrequest',
            name='start_time',
            field=models.TimeField(default='09:00', verbose_name='Начало смены'),
        ),
        migrations.AlterField(
            model_name='shiftrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Утверждено'), ('rejected', 'Отклонено')], default='pending', max_length=20),
        ),
        migrations.RemoveField(
            model_name='shiftrequest',
            name='shift',
        ),
    ]
