# Generated by Django 5.1.5 on 2025-06-01 01:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0018_alter_shiftrequest_date_alter_shiftrequest_end_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='shifts', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники'),
        ),
    ]
