# Generated by Django 5.1.5 on 2025-01-25 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='age',
            new_name='child_age',
        ),
        migrations.RenameField(
            model_name='child',
            old_name='name',
            new_name='child_name',
        ),
    ]
