# Generated by Django 5.1.5 on 2025-01-31 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Клиент'), ('STAFF', 'Сотрудник'), ('MANAGER', 'Менеджер'), ('ADMIN', 'Администратор')], default='CLIENT', max_length=10, verbose_name='Роль'),
        ),
    ]
