# Generated by Django 5.1.5 on 2025-05-31 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_child_options_alter_child_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='professional_role',
            field=models.CharField(choices=[('none', 'Не назначена'), ('animator', 'Детский городок'), ('additional', 'Доп. сотрудник'), ('vr_operator', 'VR сотрудник'), ('cashier', 'Кассир (Администратор)')], default='none', max_length=20, verbose_name='Профессиональная роль'),
        ),
    ]
